sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - polymer install --variants

before_script:

script:
  - mv bower_components-polymer2 bower_components
  - cp bower-polymer2.json bower.json
  - cp wct.conf-2.0.js wct.conf.js
  - # (see iron-input #104) cp test/index-2.0.html test/index.html
  - xvfb-run -s '-screen 0 1024x768x24' wct
